import 'package:diabeatthis/core/domain/model/device_status.dart';

DeviceStatus testDeviceStatus({
  String? externalId,
  DeviceStatusSource source = DeviceStatusSource.cloud,
  required DateTime date,
  required double iob,
  double basalIob = 0,
  double bolusIob = 0,
  double insulinActivity = 0,
  required double cob,
  required String tick,
  required int bg,
  double carbsReq = 0,
  int carbsReqWithin = 0,
  double sensitivityRatio = 1,
  double isfMgdlForCarbs = 0,
  double baseBasalRate = 0,
  int tempBasalRemainingMinutes = 0,
  double lastBolusAmount = 0,
  String lastBolusAt = '',
}) {
  return DeviceStatus(
    externalId: externalId,
    source: source,
    date: date,
    iob: iob,
    basalIob: basalIob,
    bolusIob: bolusIob,
    insulinActivity: insulinActivity,
    cob: cob,
    tick: tick,
    bg: bg,
    carbsReq: carbsReq,
    carbsReqWithin: carbsReqWithin,
    sensitivityRatio: sensitivityRatio,
    isfMgdlForCarbs: isfMgdlForCarbs,
    baseBasalRate: baseBasalRate,
    tempBasalRemainingMinutes: tempBasalRemainingMinutes,
    lastBolusAmount: lastBolusAmount,
    lastBolusAt: lastBolusAt,
  );
}
